[theme]
# shades of purple
primaryColor="#fad000"
backgroundColor="#28284e"
secondaryBackgroundColor="#222145"
textColor="#ffffff"
font="sans serif"

[server]
# port = 8501
# headless = true
# for local development:
runOnSave = true
# if running docker on windows host:
# fileWatcherType = "poll"
